name: Docs
# By a huge margin the slowest test, so we run it separately

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Run tests with all features
    - name: Run complete tests
      run: cargo test --features "default,snapshot_builder,fs_import,url_import,web,os_exit" --doc
