name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Run tests with no features
    - name: Run barebones tests
      run: cargo test --no-default-features --lib

    # Run default feature tests
    - name: Run tests
      run: cargo test --verbose --lib

    # Run tests with just web feature
    - name: Run web tests
      run: cargo test --features "web" --lib

    # Run tests with used features
    - name: Run complete tests
      run: cargo test --features "default,snapshot_builder,fs_import,url_import,web,os_exit" --lib
